In [5]:
import pandas as pd
from os.path import join as path_join

In [ ]:
nci60 = pd.read_csv(path_join("data", "DOSERESP.csv"))
print(nci60.shape)
nci60.head()

In [2]:
nci60.loc[nci60["NSC"] == 1].loc[nci60["CELL_NAME"] == "CCRF-CEM"].sort_values(by=["EXPID", "CONCENTRATION"])

,RELEASE_DATE,EXPID,PREFIX,NSC,CONCENTRATION_UNIT,LOG_HI_CONCENTRATION,CONCENTRATION,PANEL_NUMBER,CELL_NUMBER,PANEL_NAME,CELL_NAME,PANEL_CODE,COUNT_GIPRCNT,AVERAGE_GIPRCNT,STDDEV_GIPRCNT,COUNT_PTC,AVERAGE_PTC,STDDEV_PTC
1559974,20210223,0807NS58,S,1,M,-4.0,-8.0,7,3,Leukemia,CCRF-CEM,LEU,1,91.7730,0.0,1,93.7922,0.0
8427425,20210223,0807NS58,S,1,M,-4.0,-7.0,7,3,Leukemia,CCRF-CEM,LEU,1,96.4364,0.0,1,97.3009,0.0
2015337,20210223,0807NS58,S,1,M,-4.0,-6.0,7,3,Leukemia,CCRF-CEM,LEU,1,87.9894,0.0,1,90.8232,0.0
14913508,20210223,0807NS58,S,1,M,-4.0,-5.0,7,3,Leukemia,CCRF-CEM,LEU,1,0.8799,0.0,1,24.0216,0.0
14139974,20210223,0807NS58,S,1,M,-4.0,-4.0,7,3,Leukemia,CCRF-CEM,LEU,1,-42.4855,0.0,1,13.4953,0.0
13552026,20210223,0809RS22,S,1,M,-3.0,-7.0,7,3,Leukemia,CCRF-CEM,LEU,1,61.6454,0.0,1,71.4286,0.0
3769569,20210223,0809RS22,S,1,M,-3.0,-6.0,7,3,Leukemia,CCRF-CEM,LEU,1,63.3358,0.0,1,72.6050,0.0
14496190,20210223,0809RS22,S,1,M,-3.0,-5.0,7,3,Leukemia,CCRF-CEM,LEU,1,31.1044,0.0,1,48.5714,0.0
6510296,20210223,0809RS22,S,1,M,-3.0,-4.0,7,3,Leukemia,CCRF-CEM,LEU,1,29.9775,0.0,1,47.7311,0.0
12672563,20210223,0809RS22,S,1,M,-3.0,-3.0,7,3,Leukemia,CCRF-CEM,LEU,1,74.2675,0.0,1,80.8403,0.0
8725608,20210223,0810RS52,S,1,M,-3.0,-7.0,7,3,Leukemia,CCRF-CEM,LEU,1,127.0292,0.0,1,118.2203,0.0
8400215,20210223,0810RS52,S,1,M,-3.0,-6.0,7,3,Leukemia,CCRF-CEM,LEU,1,126.2411,0.0,1,117.7966,0.0
11691625,20210223,0810RS52,S,1,M,-3.0,-5.0,7,3,Leukemia,CCRF-CEM,LEU,1,-53.8710,0.0,1,15.2542,0.0
6833516,20210223,0810RS52,S,1,M,-3.0,-4.0,7,3,Leukemia,CCRF-CEM,LEU,1,-49.6774,0.0,1,16.5254,0.0
14963660,20210223,0810RS52,S,1,M,-3.0,-3.0,7,3,Leukemia,CCRF-CEM,LEU,1,-40.0000,0.0,1,19.7034,0.0

In [7]:
chem_names = pd.read_csv(path_join("data", "chemnames_Aug2013.txt"), "|", header=None, names=["NSC", "Name", "Name Type"])
chem_names.loc[chem_names["NSC"] == 1]

    NSC                                     Name      Name Type
0     1                             Tolylquinone  Chemical Name
1     1                            p-Toluquinone  Chemical Name
2     1                            Methylquinone  Chemical Name
3     1                          1,4-Toluquinone  Chemical Name
4     1                          2-Methylquinone  Chemical Name
5     1                       Methylbenzoquinone  Chemical Name
6     1                     2-Methyl-1,4-quinone  Chemical Name
7     1                     2-Methylbenzoquinone  Chemical Name
8     1                    Methyl-p-benzoquinone  Chemical Name
9     1                  Methyl-1,4-benzoquinone  Chemical Name
10    1                  2-Methyl-p-benzoquinone  Chemical Name
11    1                 2-Methylbenzoquinone-1,4  Chemical Name
12    1                2-Methyl-1,4-benzoquinone  Chemical Name
13    1                          WLN: L6V DVJ B1  Chemical Name
14    1  2,5-Cyclohexadiene-1,4-dione, 2-methyl-       9th C.I.
15    1                p-Benzoquinone, 2-methyl-       8th C.I.
16    1                              Toluquinone            VAN

In [12]:
chem_names.loc[chem_names["NSC"] == 191295]

Empty DataFrame
Columns: [NSC, Name, Name Type]
Index: []

In [4]:
gi50 = pd.read_csv(path_join("data", "GI50.csv"))
print(gi50.shape)
gi50.head()

(4547757, 14)

,RELEASE_DATE,EXPID,PREFIX,NSC,CONCENTRATION_UNIT,LOG_HI_CONCENTRATION,PANEL_NUMBER,CELL_NUMBER,PANEL_NAME,CELL_NAME,PANEL_CODE,COUNT,AVERAGE,STDDEV
0,20210223,0804NS72,S,745455,M,-4.0,10,7,Melanoma,SK-MEL-5,MEL,1,-5.1652,0.0
1,20210223,0804NS72,S,745455,M,-4.0,10,8,Melanoma,SK-MEL-28,MEL,1,-4.0000,0.0
2,20210223,0804NS72,S,745455,M,-4.0,10,14,Melanoma,M14,MEL,1,-5.3654,0.0
3,20210223,0804NS72,S,745455,M,-4.0,10,20,Melanoma,UACC-62,MEL,1,-4.0000,0.0
4,20210223,0804NS72,S,745455,M,-4.0,10,21,Melanoma,UACC-257,MEL,1,-4.0000,0.0

In [5]:
lc50 = pd.read_csv(path_join("data", "LC50.csv"))
print(lc50.shape)
lc50.head()

(4525770, 14)

,RELEASE_DATE,EXPID,PREFIX,NSC,CONCENTRATION_UNIT,LOG_HI_CONCENTRATION,PANEL_NUMBER,CELL_NUMBER,PANEL_NAME,CELL_NAME,PANEL_CODE,COUNT,AVERAGE,STDDEV
0,20210223,0412NS76,S,19893,M,-2.6021,5,6,Breast Cancer,HS 578T,BRE,1,-2.6021,0.0
1,20210223,0412NS76,S,19893,M,-2.6021,5,11,Melanoma,MDA-MB-435,MEL,1,-2.6021,0.0
2,20210223,0412NS76,S,19893,M,-2.6021,5,14,Breast Cancer,T-47D,BRE,1,-2.6021,0.0
3,20210223,0412NS76,S,19893,M,-2.6021,6,1,Ovarian Cancer,OVCAR-3,OVA,1,-2.6021,0.0
4,20210223,0412NS76,S,19893,M,-2.6021,6,2,Ovarian Cancer,OVCAR-4,OVA,1,-2.6021,0.0

In [6]:
tgi = pd.read_csv(path_join("data", "TGI.csv"))
print(tgi.shape)
tgi.head()

(4535722, 14)

,RELEASE_DATE,EXPID,PREFIX,NSC,CONCENTRATION_UNIT,LOG_HI_CONCENTRATION,PANEL_NUMBER,CELL_NUMBER,PANEL_NAME,CELL_NAME,PANEL_CODE,COUNT,AVERAGE,STDDEV
0,20210223,9212EM18,S,645812,M,-4.0,12,9,CNS Cancer,U251,CNS,1,-4.6886,0.0
1,20210223,9212EM18,S,645812,M,-4.0,12,14,CNS Cancer,SF-268,CNS,1,-4.7078,0.0
2,20210223,9212EM18,S,645812,M,-4.0,12,15,CNS Cancer,SF-295,CNS,1,-4.7296,0.0
3,20210223,9212EM18,S,645812,M,-4.0,12,16,CNS Cancer,SF-539,CNS,1,-4.5765,0.0
4,20210223,9212EM18,S,645813,M,-4.0,1,1,Non-Small Cell Lung Cancer,NCI-H23,LNS,1,-4.6972,0.0

In [11]:
print("unique nsc in raw data", len(nci60["NSC"].unique()))
print("unique nsc in gi50 data", len(gi50["NSC"].unique()))
print("unique nsc in lc50 data", len(lc50["NSC"].unique()))
print("unique nsc in tgi data", len(tgi["NSC"].unique()))

unique nsc in raw data 56223
unique nsc in gi50 data 56220
unique nsc in lc50 data 56220
unique nsc in tgi data 56218

In [13]:
nci60.groupby("EXPID").count()

,RELEASE_DATE,PREFIX,NSC,CONCENTRATION_UNIT,LOG_HI_CONCENTRATION,CONCENTRATION,PANEL_NUMBER,CELL_NUMBER,PANEL_NAME,CELL_NAME,PANEL_CODE,COUNT_GIPRCNT,AVERAGE_GIPRCNT,STDDEV_GIPRCNT,COUNT_PTC,AVERAGE_PTC,STDDEV_PTC
EXPID,,,,,,,,,,,,,,,,,
0001MD02,575,575,575,575,575,575,575,575,575,575,575,575,575,575,575,575,575
0001MD03,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300
0001MD05,7325,7325,7325,7325,7325,7325,7325,7325,7325,7325,7325,7325,7325,7325,7325,7325,7325
0001MD07,570,570,570,570,570,570,570,570,570,570,570,570,570,570,570,570,570
0001MD08,7060,7060,7060,7060,7060,7060,7060,7060,7060,7060,7060,7060,7060,7060,7060,7060,7060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9912MD97,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560
9912MD98,3425,3425,3425,3425,3425,3425,3425,3425,3425,3425,3425,3425,3425,3425,3425,3425,3425
9912NS97,1100,1100,1100,1100,1100,1100,1100,1100,1100,1100,1100,1100,1100,1100,1100,1100,1100
9912NS98,4799,4799,4799,4799,4799,4799,4799,4799,4799,4799,4799,4799,4799,4799,4799,4799,4799
9912RS98,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160,1160

In [25]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
gi50.groupby("CELL_NAME").count().sort_values(["NSC"])["NSC"]

CELL_NAME
NYH                    1
CHO                    2
NYH/ICRF-187-1         2
CHO/159-1              2
VDSO/CMV-8             2
VDSO/E6-18             2
MDA-MB-435S            3
CCD-19LU               3
VDSO/CMV-9             3
VDSO/E6-19             3
Mar-Bel                4
TE85                   4
VDSO/P                 4
WI-38                  5
ZR-75-30               9
A-JUN 3               10
A-CREB 2              10
A-C/EBP 3             10
A431                  10
A-CREB 1              10
A-FOS 3               10
A-FOS 2               10
A-JUN 1               10
SW 1783               11
MLI-019               12
LXFS 650L             14
CHA-59                15
A-204                 16
MLI-045               16
MLI-076               16
CALU-1                16
NB4                   16
ZR-75-1               17
MCF7/ATCC             17
RXF 486L              17
RPMI-7951             17
SF-767                17
SMS-KCNR              17
SW 1088               17
UABLG22               17
UABMEL3               17
UOK-57                17
ND-1                  17
JCA-1                 17
MLI-059               17
CACO-2                17
ES-2 CNCR             17
TSU-PRI               18
HCT-116/E6-2          21
HCT-116/PV            31
MEXF 514L             35
CXF 264L              35
COLO 746              35
SW-1573               36
RL                    36
HCT-116/P21/C         36
COLO 741              36
UISO-BCA-1            36
HCT-116/P21/A         43
HT29p53RE22           45
T47D ERE4             46
HCT-116/P21/B         47
T47D NFkB15           47
T47D FOS1             48
RKO Waf1              48
H1299p53RE29          48
MCF7-E6               48
RKOp53RE1             48
HCT-116/CMV-1         49
HCT-116/E6-1          53
HCT-116/P             54
HCT-116/CMV-2         54
TK-164                56
HT                    60
SW-156                71
DB                    88
MAXF 401             210
SK-BR-3              230
U-373/H.Fine         752
U118/H.Fine          782
LN-229/H.Fine        792
T98G/H.Fine          794
U-87/H.Fine          797
A-172/H.Fine         797
U-251/H.Fine         798
P388                3628
P388/ADR            3640
SN12K1              4486
MDA-MB-468         13409
RXF-631            13980
HOP-18             16875
LXFL 529           17667
XF 498             18224
DMS 273            19952
SNB-78             20550
KM20L2             21491
DMS 114            21702
DLD-1              22023
M19-MEL            22945
MDA-N              38104
BT-549             50684
T-47D              52796
HS 578T            53370
MDA-MB-231/ATCC    56233
PC-3               56686
DU-145             56866
MDA-MB-435         57072
MCF7               60162
SR                 60891
NCI/ADR-RES        61103
A498               68105
HOP-92             68495
HCC-2998           69882
RXF 393            70225
HL-60(TB)          70640
MALME-3M           71940
NCI-H522           72470
NCI-H226           72537
RPMI-8226          72982
CAKI-1             73034
SNB-75             73111
TK-10              73217
SK-MEL-2           73482
EKVX               74028
CCRF-CEM           74483
OVCAR-4            74584
LOX IMVI           74603
M14                74619
786-0              74673
SK-OV-3            74905
ACHN               74968
SF-539             75005
NCI-H322M          75997
HOP-62             76668
K-562              76708
UACC-257           76923
OVCAR-3            77207
MOLT-4             77498
SK-MEL-5           77560
UACC-62            77611
SK-MEL-28          77614
NCI-H460           77846
OVCAR-5            78044
IGROV1             78246
HT29               78286
COLO 205           78289
UO-31              78397
SF-268             78542
SNB-19             78548
SF-295             78580
SN12C              78835
KM12               79024
HCT-15             79039
HCT-116            79068
NCI-H23            79110
U251               79543
SW-620             79852
OVCAR-8            79963
A549/ATCC          80456
Name: NSC, dtype: int64